# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5362596f658df93af2fa6e642621646411a3b5e8351b912ebcfb1675906388341eb9871e9c55b9ab9c5112942892e3d2ccd84f5e7b6ba39dc865a51a4355fe6a

test:
  secret_key_base: c0bbbf4f0810cd94a668f8aa65eda11da364fe0ff48da0c8357591b295315e064faaea9da302d01381f2245db44b2c1cce6e9eb0c42eb5fa9fde18b3614799cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
