Play.create(name:'thor', time:06-30-2014, location:'san fran', description:'thor dominates society by killing off courpt cops')
Play.create(name:'batman', time:06-30-2014, location:'salt lake city', description:'the master of being a vigilante')
Play.create(name:'sipderman', time:06-30-2014, location:'washington dc', description:'superhero in love')
Play.create(name:'superman', time:06-30-2014, location:'shit all over', description:'this dude moves quick')
Play.create(name:'silver surfer', time:06-30-2014, location:'world wide', description:'moving at the speed of light')
